version: "3"
networks:
  XXXXX_network:
    driver: bridge
services:
  app:
    container_name: XXXXX_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    networks:
      - XXXXX_network