version: "3"
services:
  app:
    container_name: ***_app
    extra_hosts:
      - host.docker.internal:host-gateway
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VAR: 16
        USERNAME: node
        USER_UID: 1000
        USER_GID: 1000
    command: sleep infinity
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.ssh:/home/node/.ssh
