version: "3"
services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONTAINER_OS: ${CONTAINER_OS}
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity
    ports:
      - 3000:3000
      - 4200:4200
      - 9222:9222
