version: '3'
services:
  app:
    container_name: XXXXX__app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=node
        - USER_UID=1000
        - USER_GID=1000
    network_mode: 'host'
    command: sleep infinity
    environment:
      TZ: Asia/Tokyo
    volumes:
      - XXXXX_node_modules:/workspace/node_modules
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh
volumes:
  XXXXX_node_modules:
