version: "3"
services:
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: node
        USER_UID: 1000
        USER_GID: 1000
    command: sleep infinity
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.ssh:/home/node/.ssh