version: "3"
services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ${NODE_VERSION}
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity
    ports:
      - 3000:3000
      - 4200:4200
      - 9222:9222
