services:
  web:
    container_name: ***_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VAR: 14
        USER_SID: root
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
      - ~/.netrc:/root/.netrc
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    ports:
      - 3000:3000
      - 4200:4200